# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    desc: Displays all available tasks.
    cmds:
      - task --list-all --sort none

  environment:check:
    desc: Check required tools are available for this environment.
    cmds:
      - python --version
      - python3 --version
      - task --version
      - uv --version

  code:check:
    desc: Check the codebase.
    deps:
      - code:lint
      - code:test

  code:lint:
    desc: Lint the codebase.
    cmds:
      - uv run ruff check .

  code:test:
    desc: Test the codebase.
    cmds:
      - uv run pytest .
